language: node_js
node_js:
  - '10'
install:
  - npm install -g codecov
  - npm install -g prettier
script:
  - npm install
  - npm run lint
  - npm run test:coverage --runInBand --no-cache
  - npm test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
